next_seq: 11
robots:
  4:
    success: 1
    failure: 0
    last_seq: 8
  6:
    success: 1
    failure: 0
    last_seq: 4
  5:
    success: 2
    failure: 0
    last_seq: 10
  1:
    success: 2
    failure: 0
    last_seq: 6
  8:
    success: 0
    failure: 1
    last_seq: 3
  3:
    success: 0
    failure: 1
    last_seq: 5
  2:
    success: 1
    failure: 0
    last_seq: 7
  7:
    success: 1
    failure: 0
    last_seq: 9