services:
  web-debugger:
    build:
      context: ../..
      dockerfile: docker/dev/web-debugger/Dockerfile
    container_name: crane-web-debugger
    network_mode: host
    environment:
      - HTTP_PORT=8090
    restart: unless-stopped

  ball-calibration:
    build:
      context: ./ball-calibration
    container_name: crane-ball-calibration
    network_mode: host
    environment:
      - HTTP_PORT=8093
      - DISPLAY=${DISPLAY}
    volumes:
      - /home:/home:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    restart: unless-stopped

  robot-manager:
    image: ghcr.io/ibis-ssl/robot-manager:latest
    container_name: crane-robot-manager
    network_mode: host
    environment:
      - HTTP_PORT=8092
      - NUM_ROBOTS=13
      - ROBOT_IP_BASE=192.168.20.
      - ROBOT_IP_OFFSET=100
      - ROBOT_PORT=8000
      - HTTP_TIMEOUT_SEC=0.8
      - BACK_URL=http://localhost:8090
    restart: unless-stopped

  erforce-sim:
    image: ghcr.io/ibis-ssl/framework-simulatorcli:latest
    container_name: erforce-sim
    network_mode: host
    entrypoint: ["tini", "--"]
    command: >
      ./bin/simulator-cli
      -g 2023
      --realism Realistic
      --ibis-use-referee
      --ibis-feedback-team-name ibis
      --ibis-referee-port 11003
    restart: "no"
    profiles:
      - sim-erforce

  grsim:
    image: ghcr.io/ibis-ssl/grsim:latest
    container_name: grsim
    network_mode: host
    command: |
      grSim --headless -platform offscreen
    volumes:
      - ./grsim.xml:/home/default/.grsim.xml:rw
    tty: true
    stdin_open: true
    restart: "no"
    profiles:
      - sim-grsim

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:latest
    command:
      - -visionAddress
      - 224.5.23.2:${VISION_PORT:-10020}
      - -trackerAddress
      - 224.5.23.2:11010 # not yet overridable by autoRefs
      - -publishAddress
      - 224.5.23.1:11003
      - -address
      - :8081
    volumes:
      - ./config:/config:rw
    network_mode: host

  ssl-vision-client:
    image: ghcr.io/ibis-ssl/ssl-vision-client:develop
    command:
      - -address
      - :8082
    volumes:
      - ./ssl-vision-client-config.json:/config.json:rw
    network_mode: host

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.12.3
    command:
      - -address
      - :8083
      - --refereeAddress
      - 224.5.23.1:11003
    network_mode: host
    profiles:
      - sim-erforce
      - sim-grsim

  autoref-tigers:
    image: tigersmannheim/auto-referee:1.2.0
    command:
      - --active # active mode (connect to GC)
      - --headless
      - --visionAddress
      - 224.5.23.2:${VISION_PORT:-10020}
      - --refereeAddress
      - 224.5.23.1:11003
      - --trackerAddress
      - 224.5.23.2:11010
    network_mode: host

  ssl-log-recorder:
    image: robocupssl/ssl-log-recorder:latest
    container_name: crane-ssl-log-recorder
    network_mode: host
    restart: "no"
    stop_signal: SIGINT
    stop_grace_period: 30s
    volumes:
      - ../../:/logs
    working_dir: /logs
    command:
      - -referee-address
      - "224.5.23.1:${REFEREE_PORT:-11003}"
      - -vision-address
      - "224.5.23.2:${VISION_PORT:-10020}"
      - -vision-tracker-address
      - "224.5.23.2:${TRACKER_PORT:-11010}"
      - -vision-legacy-enabled=false

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    # image: voicevox/voicevox_engine:nvidia-latest
    ports:
      - 127.0.0.1:50021:50021
