grsim_operator:
  ros__parameters:
    ball:
      pos: [0,0]
      vel: [0,0]
    yellow:
        robot1: [0.4,4.65,0.0]
        robot2: [0.8,4.65,0.0]
        robot3: [1.2,4.65,0.0]
        robot4: [1.6,4.65,0.0]
        robot5: [2.0,4.65,0.0]
        robot6: [2.4,4.65,0.0]
        robot7: [2.8,4.65,0.0]
        robot8: [3.2,4.65,0.0]
    blue:
        robot1: [-0.4,-4.65,0.0]
        robot2: [-0.8,-4.65,0.0]
        robot3: [-1.2,-4.65,0.0]
        robot4: [-1.6,-4.65,0.0]
        robot5: [-2.0,-4.65,0.0]
        robot6: [-2.4,-4.65,0.0]
        robot7: [-2.8,-4.65,0.0]
        robot8: [-3.2,-4.65,0.0]
