variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "true"
  GIT_SUBMODULE_STRATEGY: recursive
  DEBIAN_FRONTEND: noninteractive
image: ibisssl/ros2-dashing
stages:
  - build

job:
  stage: build
  script:
    - apt-get update
    # - apt-get upgrade -y
    - mkdir -p ~/ros2_ws/src/crane
    - cp -rf . ~/ros2_ws/src/crane
    - cd ~/ros2_ws/src
    - git clone --recursive --depth 1 https://github.com/ibis-ssl/consai2r2.git
    - apt-get install -y python-rosdep wget
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/liborocos-bfl0.8_0.8.0-5_amd64.deb
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/liborocos-bfl-dev_0.8.0-5_amd64.deb
    - dpkg -i liborocos-bfl0.8_0.8.0-5_amd64.deb
    - dpkg -i liborocos-bfl-dev_0.8.0-5_amd64.deb
    - rosdep init
    - rosdep update
    - rosdep install -r -y --from-paths . --ignore-src
    - source /opt/ros/dashing/setup.bash
    - cd ~/ros2_ws
    - colcon build
    - source ~/ros2_ws/install/setup.bash
    - colcon test
    - colcon test-result --verbose
  # artifacts:
  #   paths:
  #     -
