services:
#  ssl-game-controller:
#    image: robocupssl/ssl-game-controller:3.11.2
#    command:
#      - -visionAddress
#      - 224.5.23.2:10020
#      - -trackerAddress
#      - 224.5.23.2:11010 # not yet overridable by autoRefs
#      - -publishAddress
#      - 224.5.23.1:11003
#      - -address
#      - :8081
#    volumes:
#      - ./config:/config:rw
#    network_mode: host
#    ports:
#      - 8081:8081/tcp
  ssl-game-controller-private:
    image: robocupssl/ssl-game-controller:3.9.0
    command:
      - "-visionAddress"
      - "224.5.23.2:11006"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    volumes:
      - ./config:/config:rw
    ports:
      - 8081/tcp
    networks:
      - referee
      - expose

  ssl-game-controller-public:
    image: g3force/proxy-tcp-udp-mc:0.2.1
    command:
      - "tcp,:10007,ssl-game-controller-private:10007,AutoRef"
      - "tcp,:10008,ssl-game-controller-private:10008,Team"
      - "tcp,:10011,ssl-game-controller-private:10011,RemoteCtrl"
      - "mc,224.5.23.1:11003,224.5.23.1:10003,Referee"
      - "mc,224.5.23.2:10006,224.5.23.2:11006,Vision"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    ports:
      - 10007/tcp
      - 10008/tcp
      - 10011/tcp
    networks:
      - referee
      - match

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.7.3
    command: [ "-visionAddress", "224.5.23.2:10006" ]
    restart: unless-stopped
    ports:
      - 8082/tcp
    networks:
      - match
      - expose

  ssl-status-board:
    image: robocupssl/ssl-status-board:2.10.4
    restart: unless-stopped
    ports:
      - 8082/tcp
    networks:
      - match
      - expose
#  ssl-vision-client:
#    image: robocupssl/ssl-vision-client:1.6.0
#    command:
#      - -address
#      - :8082
#      - -visionAddress
#      - 224.5.23.2:10020
#    network_mode: host
#    ports:
#      - 8082:8082/tcp
#  ssl-status-board:
#    image: robocupssl/ssl-status-board:2.11.5
#    command:
#      - -address
#      - :8083
#      - --refereeAddress
#      - 224.5.23.1:11003
#    network_mode: host
#    ports:
#      - 8083:8083/tcp

  autoref-tigers:
    image: tigersmannheim/auto-referee:1.2.0
    command:
      - --active # active mode (connect to GC)
      - --headless
      - --visionAddress
      - 224.5.23.2:10020
      - --refereeAddress
      - 224.5.23.1:11003
      - --trackerAddress
      - 224.5.23.2:11010
    networks:
      - match

  simulator:
    image: g3force/proxy-tcp-udp-mc:0.2.1
    command:
      - "udp,:10301,simulator-private:10301,Blue"
      - "udp,:10302,simulator-private:10302,Yellow"
      - "mc,224.5.23.2:10020,224.5.23.2:10006,Vision"
      - "mc,224.5.23.1:10003,224.5.23.1:11003,Referee"
      - "mc,224.5.23.2:10010,224.5.23.2:11010,Tracker"
    restart: unless-stopped
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
    networks:
      - simulator
      - match
  simulator-private:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
#    restart: unless-stopped
    environment:
      # ER-Force options
      GEOMETRY: "2023"
      REALISM: "RC2021"
    ports:
      - 10300/udp
      - 10301/udp
      - 10302/udp
      - 10020/udp
      - 10006/udp
    networks:
      - simulator

  ssl-simulation-controller:
    image: robocupssl/ssl-simulation-controller:0.12.1
    command:
      - "-refereeAddress"
      - "224.5.23.1:11003"
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-simControlPort"
      - "10300"
      - "-robotSpecConfig"
      - "/config/robot-specs.yaml"
    restart: unless-stopped
    volumes:
      - ./config/ssl-simulation-controller:/config:ro
    networks:
      - simulator


#  voicevox:
#    image: voicevox/voicevox_engine:cpu-latest
##    image: voicevox/voicevox_engine:nvidia-latest
#    ports:
#      - 127.0.0.1:50021:50021

networks:
  match:
  simulator:
  referee:
  expose:
