services:
  ssl-vision-client:
    image: ghcr.io/ibis-ssl/ssl-vision-client:develop
    command:
      - -address
      - :8082
    volumes:
      - ./ssl-vision-client-config.json:/config.json:rw
    network_mode: host
    ports:
      - 8082:8082/tcp
