services:
  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.6.0
    command:
      - -address
      - :8082
      - -visionAddress
      - 224.5.23.2:11006
    network_mode: host
    ports:
      - 8082:8082/tcp