{
  "gameEventBehavior":  {
    "AIMLESS_KICK":  "BEHAVIOR_ACCEPT",
    "ATTACKER_DOUBLE_TOUCHED_BALL":  "BEHAVIOR_ACCEPT",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
    "BALL_LEFT_FIELD_GOAL_LINE":  "BEHAVIOR_ACCEPT",
    "BALL_LEFT_FIELD_TOUCH_LINE":  "BEHAVIOR_ACCEPT",
    "BOT_CRASH_DRAWN":  "BEHAVIOR_ACCEPT",
    "BOT_CRASH_UNIQUE":  "BEHAVIOR_ACCEPT",
    "BOT_DRIBBLED_BALL_TOO_FAR":  "BEHAVIOR_ACCEPT",
    "BOT_DROPPED_PARTS":  "BEHAVIOR_ACCEPT",
    "BOT_HELD_BALL_DELIBERATELY":  "BEHAVIOR_ACCEPT",
    "BOT_INTERFERED_PLACEMENT":  "BEHAVIOR_ACCEPT",
    "BOT_KICKED_BALL_TOO_FAST":  "BEHAVIOR_ACCEPT",
    "BOT_PUSHED_BOT":  "BEHAVIOR_ACCEPT",
    "BOT_SUBSTITUTION":  "BEHAVIOR_ACCEPT",
    "BOT_TIPPED_OVER":  "BEHAVIOR_ACCEPT",
    "BOT_TOO_FAST_IN_STOP":  "BEHAVIOR_ACCEPT",
    "BOUNDARY_CROSSING":  "BEHAVIOR_ACCEPT",
    "CHALLENGE_FLAG":  "BEHAVIOR_ACCEPT",
    "CHALLENGE_FLAG_HANDLED":  "BEHAVIOR_ACCEPT",
    "DEFENDER_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT":  "BEHAVIOR_ACCEPT",
    "EMERGENCY_STOP":  "BEHAVIOR_ACCEPT",
    "EXCESSIVE_BOT_SUBSTITUTION":  "BEHAVIOR_ACCEPT",
    "GOAL":  "BEHAVIOR_ACCEPT",
    "INVALID_GOAL":  "BEHAVIOR_ACCEPT",
    "KEEPER_HELD_BALL":  "BEHAVIOR_ACCEPT",
    "MULTIPLE_CARDS":  "BEHAVIOR_ACCEPT",
    "MULTIPLE_FOULS":  "BEHAVIOR_ACCEPT",
    "NO_PROGRESS_IN_GAME":  "BEHAVIOR_ACCEPT",
    "PENALTY_KICK_FAILED":  "BEHAVIOR_ACCEPT",
    "PLACEMENT_FAILED":  "BEHAVIOR_ACCEPT",
    "PLACEMENT_SUCCEEDED":  "BEHAVIOR_ACCEPT",
    "POSSIBLE_GOAL":  "BEHAVIOR_ACCEPT",
    "TOO_MANY_ROBOTS":  "BEHAVIOR_ACCEPT",
    "UNSPORTING_BEHAVIOR_MAJOR":  "BEHAVIOR_ACCEPT",
    "UNSPORTING_BEHAVIOR_MINOR":  "BEHAVIOR_ACCEPT"
  },
  "autoRefConfigs":  {
    "ER-Force":  {
      "gameEventBehavior":  {
        "AIMLESS_KICK":  "BEHAVIOR_ACCEPT",
        "ATTACKER_DOUBLE_TOUCHED_BALL":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_GOAL_LINE":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_TOUCH_LINE":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_DRAWN":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_UNIQUE":  "BEHAVIOR_ACCEPT",
        "BOT_DRIBBLED_BALL_TOO_FAR":  "BEHAVIOR_ACCEPT",
        "BOT_HELD_BALL_DELIBERATELY":  "BEHAVIOR_ACCEPT",
        "BOT_INTERFERED_PLACEMENT":  "BEHAVIOR_ACCEPT",
        "BOT_KICKED_BALL_TOO_FAST":  "BEHAVIOR_ACCEPT",
        "BOT_PUSHED_BOT":  "BEHAVIOR_ACCEPT",
        "BOT_TIPPED_OVER":  "BEHAVIOR_ACCEPT",
        "BOT_TOO_FAST_IN_STOP":  "BEHAVIOR_ACCEPT",
        "BOUNDARY_CROSSING":  "BEHAVIOR_ACCEPT",
        "DEFENDER_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "DEFENDER_TOO_CLOSE_TO_KICK_POINT":  "BEHAVIOR_ACCEPT",
        "GOAL":  "BEHAVIOR_ACCEPT",
        "INVALID_GOAL":  "BEHAVIOR_ACCEPT",
        "KEEPER_HELD_BALL":  "BEHAVIOR_ACCEPT",
        "NO_PROGRESS_IN_GAME":  "BEHAVIOR_ACCEPT",
        "PENALTY_KICK_FAILED":  "BEHAVIOR_ACCEPT",
        "PLACEMENT_FAILED":  "BEHAVIOR_ACCEPT",
        "PLACEMENT_SUCCEEDED":  "BEHAVIOR_ACCEPT",
        "POSSIBLE_GOAL":  "BEHAVIOR_ACCEPT",
        "TOO_MANY_ROBOTS":  "BEHAVIOR_ACCEPT"
      }
    },
    "TIGERs AutoRef":  {
      "gameEventBehavior":  {
        "AIMLESS_KICK":  "BEHAVIOR_ACCEPT",
        "ATTACKER_DOUBLE_TOUCHED_BALL":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_GOAL_LINE":  "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_TOUCH_LINE":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_DRAWN":  "BEHAVIOR_ACCEPT",
        "BOT_CRASH_UNIQUE":  "BEHAVIOR_ACCEPT",
        "BOT_DRIBBLED_BALL_TOO_FAR":  "BEHAVIOR_ACCEPT",
        "BOT_DROPPED_PARTS":  "BEHAVIOR_ACCEPT",
        "BOT_HELD_BALL_DELIBERATELY":  "BEHAVIOR_ACCEPT",
        "BOT_INTERFERED_PLACEMENT":  "BEHAVIOR_ACCEPT",
        "BOT_KICKED_BALL_TOO_FAST":  "BEHAVIOR_ACCEPT",
        "BOT_PUSHED_BOT":  "BEHAVIOR_ACCEPT",
        "BOT_TIPPED_OVER":  "BEHAVIOR_ACCEPT",
        "BOT_TOO_FAST_IN_STOP":  "BEHAVIOR_ACCEPT",
        "BOUNDARY_CROSSING":  "BEHAVIOR_ACCEPT",
        "DEFENDER_IN_DEFENSE_AREA":  "BEHAVIOR_ACCEPT",
        "DEFENDER_TOO_CLOSE_TO_KICK_POINT":  "BEHAVIOR_ACCEPT",
        "GOAL":  "BEHAVIOR_ACCEPT",
        "INVALID_GOAL":  "BEHAVIOR_ACCEPT",
        "KEEPER_HELD_BALL":  "BEHAVIOR_ACCEPT",
        "NO_PROGRESS_IN_GAME":  "BEHAVIOR_ACCEPT",
        "PENALTY_KICK_FAILED":  "BEHAVIOR_ACCEPT",
        "PLACEMENT_FAILED":  "BEHAVIOR_ACCEPT",
        "PLACEMENT_SUCCEEDED":  "BEHAVIOR_ACCEPT",
        "POSSIBLE_GOAL":  "BEHAVIOR_ACCEPT",
        "TOO_MANY_ROBOTS":  "BEHAVIOR_ACCEPT"
      }
    }
  },
  "activeTrackerSource":  "fd715b1b-567f-4844-8bfe-ca4d7d401591",
  "teams":  [
    "OMID",
    "Warthog Robotics",
    "NAELIC",
    "CMμs",
    "ER-Force",
    "RoboTeam Twente",
    "Titans",
    "Tritons RCSC",
    "UMass Minutebots",
    "luhbots",
    "RoboDragons",
    "RFC Cambridge",
    "SSH",
    "UTBots",
    "OP-AmP",
    "AMC",
    "KgpKubs",
    "Red Dragons",
    "STOx’s",
    "Unknown",
    "Roots",
    "Ararabots",
    "Parsian",
    "Sysmic Robotics",
    "TRAPS",
    "ibis",
    "ITAndroids",
    "Pequi Mecânico",
    "RoboIME",
    "Test Team",
    "Delft Mercurians",
    "MCT Susano Logics",
    "MIT Roboteam",
    "NAMeC",
    "RoboFEI",
    "SRC",
    "Ri-One",
    "AIS",
    "A-Team",
    "Maracatronics",
    "MRL",
    "OrcaBOT",
    "TauraBOTS",
    "UBC Thunderbots",
    "Cerberus",
    "Eagles",
    "GreenTea",
    "Ri-one",
    "SeeGoals",
    "ULtron",
    "UnBall",
    "Immortals",
    "KIKS",
    "RobôCin",
    "RoboJackets",
    "NEUIslanders",
    "ZJUNlict",
    "Carrossel Caipira",
    "Junior SuperTeam",
    "The Bots",
    "TIGERs Mannheim",
    "nAMeC",
    "SPbUnited",
    "TurtleRabbit",
    "URoboRus",
    "Neon"
  ],
  "autoContinue":  false
}
