{
  "gameEventBehavior": {
    "AIMLESS_KICK": "BEHAVIOR_LOG",
    "ATTACKER_DOUBLE_TOUCHED_BALL": "BEHAVIOR_LOG",
    "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "BEHAVIOR_LOG",
    "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "BEHAVIOR_LOG",
    "BALL_LEFT_FIELD_GOAL_LINE": "BEHAVIOR_LOG",
    "BALL_LEFT_FIELD_TOUCH_LINE": "BEHAVIOR_LOG",
    "BOT_CRASH_DRAWN": "BEHAVIOR_LOG",
    "BOT_CRASH_UNIQUE": "BEHAVIOR_LOG",
    "BOT_DRIBBLED_BALL_TOO_FAR": "BEHAVIOR_LOG",
    "BOT_DROPPED_PARTS": "BEHAVIOR_LOG",
    "BOT_HELD_BALL_DELIBERATELY": "BEHAVIOR_LOG",
    "BOT_INTERFERED_PLACEMENT": "BEHAVIOR_LOG",
    "BOT_KICKED_BALL_TOO_FAST": "BEHAVIOR_LOG",
    "BOT_PUSHED_BOT": "BEHAVIOR_LOG",
    "BOT_SUBSTITUTION": "BEHAVIOR_LOG",
    "BOT_TIPPED_OVER": "BEHAVIOR_LOG",
    "BOT_TOO_FAST_IN_STOP": "BEHAVIOR_LOG",
    "BOUNDARY_CROSSING": "BEHAVIOR_LOG",
    "CHALLENGE_FLAG": "BEHAVIOR_LOG",
    "CHALLENGE_FLAG_HANDLED": "BEHAVIOR_LOG",
    "DEFENDER_IN_DEFENSE_AREA": "BEHAVIOR_LOG",
    "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "BEHAVIOR_LOG",
    "EMERGENCY_STOP": "BEHAVIOR_LOG",
    "EXCESSIVE_BOT_SUBSTITUTION": "BEHAVIOR_LOG",
    "GOAL": "BEHAVIOR_LOG",
    "INVALID_GOAL": "BEHAVIOR_LOG",
    "KEEPER_HELD_BALL": "BEHAVIOR_LOG",
    "MULTIPLE_CARDS": "BEHAVIOR_LOG",
    "MULTIPLE_FOULS": "BEHAVIOR_LOG",
    "NO_PROGRESS_IN_GAME": "BEHAVIOR_LOG",
    "PENALTY_KICK_FAILED": "BEHAVIOR_LOG",
    "PLACEMENT_FAILED": "BEHAVIOR_LOG",
    "PLACEMENT_SUCCEEDED": "BEHAVIOR_LOG",
    "POSSIBLE_GOAL": "BEHAVIOR_LOG",
    "TOO_MANY_ROBOTS": "BEHAVIOR_LOG",
    "UNSPORTING_BEHAVIOR_MAJOR": "BEHAVIOR_LOG",
    "UNSPORTING_BEHAVIOR_MINOR": "BEHAVIOR_LOG"
  },
  "autoRefConfigs": {
    "ER-Force": {
      "gameEventBehavior": {
        "AIMLESS_KICK": "BEHAVIOR_ACCEPT",
        "ATTACKER_DOUBLE_TOUCHED_BALL": "BEHAVIOR_ACCEPT",
        "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_GOAL_LINE": "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_TOUCH_LINE": "BEHAVIOR_ACCEPT",
        "BOT_CRASH_DRAWN": "BEHAVIOR_ACCEPT",
        "BOT_CRASH_UNIQUE": "BEHAVIOR_ACCEPT",
        "BOT_DRIBBLED_BALL_TOO_FAR": "BEHAVIOR_ACCEPT",
        "BOT_HELD_BALL_DELIBERATELY": "BEHAVIOR_ACCEPT",
        "BOT_INTERFERED_PLACEMENT": "BEHAVIOR_ACCEPT",
        "BOT_KICKED_BALL_TOO_FAST": "BEHAVIOR_ACCEPT",
        "BOT_PUSHED_BOT": "BEHAVIOR_ACCEPT",
        "BOT_TIPPED_OVER": "BEHAVIOR_ACCEPT",
        "BOT_TOO_FAST_IN_STOP": "BEHAVIOR_ACCEPT",
        "BOUNDARY_CROSSING": "BEHAVIOR_ACCEPT",
        "DEFENDER_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "BEHAVIOR_ACCEPT",
        "GOAL": "BEHAVIOR_ACCEPT",
        "INVALID_GOAL": "BEHAVIOR_ACCEPT",
        "KEEPER_HELD_BALL": "BEHAVIOR_ACCEPT",
        "NO_PROGRESS_IN_GAME": "BEHAVIOR_ACCEPT",
        "PENALTY_KICK_FAILED": "BEHAVIOR_ACCEPT",
        "PLACEMENT_FAILED": "BEHAVIOR_ACCEPT",
        "PLACEMENT_SUCCEEDED": "BEHAVIOR_ACCEPT",
        "POSSIBLE_GOAL": "BEHAVIOR_ACCEPT",
        "TOO_MANY_ROBOTS": "BEHAVIOR_ACCEPT"
      }
    },
    "TIGERs AutoRef": {
      "gameEventBehavior": {
        "AIMLESS_KICK": "BEHAVIOR_ACCEPT",
        "ATTACKER_DOUBLE_TOUCHED_BALL": "BEHAVIOR_ACCEPT",
        "ATTACKER_TOO_CLOSE_TO_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "ATTACKER_TOUCHED_BALL_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_GOAL_LINE": "BEHAVIOR_ACCEPT",
        "BALL_LEFT_FIELD_TOUCH_LINE": "BEHAVIOR_ACCEPT",
        "BOT_CRASH_DRAWN": "BEHAVIOR_ACCEPT",
        "BOT_CRASH_UNIQUE": "BEHAVIOR_ACCEPT",
        "BOT_DRIBBLED_BALL_TOO_FAR": "BEHAVIOR_ACCEPT",
        "BOT_DROPPED_PARTS": "BEHAVIOR_ACCEPT",
        "BOT_HELD_BALL_DELIBERATELY": "BEHAVIOR_ACCEPT",
        "BOT_INTERFERED_PLACEMENT": "BEHAVIOR_ACCEPT",
        "BOT_KICKED_BALL_TOO_FAST": "BEHAVIOR_ACCEPT",
        "BOT_PUSHED_BOT": "BEHAVIOR_ACCEPT",
        "BOT_TIPPED_OVER": "BEHAVIOR_ACCEPT",
        "BOT_TOO_FAST_IN_STOP": "BEHAVIOR_ACCEPT",
        "BOUNDARY_CROSSING": "BEHAVIOR_ACCEPT",
        "DEFENDER_IN_DEFENSE_AREA": "BEHAVIOR_ACCEPT",
        "DEFENDER_TOO_CLOSE_TO_KICK_POINT": "BEHAVIOR_ACCEPT",
        "GOAL": "BEHAVIOR_ACCEPT",
        "INVALID_GOAL": "BEHAVIOR_ACCEPT",
        "KEEPER_HELD_BALL": "BEHAVIOR_ACCEPT",
        "NO_PROGRESS_IN_GAME": "BEHAVIOR_ACCEPT",
        "PENALTY_KICK_FAILED": "BEHAVIOR_ACCEPT",
        "PLACEMENT_FAILED": "BEHAVIOR_ACCEPT",
        "PLACEMENT_SUCCEEDED": "BEHAVIOR_ACCEPT",
        "POSSIBLE_GOAL": "BEHAVIOR_ACCEPT",
        "TOO_MANY_ROBOTS": "BEHAVIOR_ACCEPT"
      }
    }
  },
  "activeTrackerSource": "fc4438a9-5bec-4ae2-9010-d3c196404533",
  "teams": [
    "ITAndroids",
    "OMID",
    "SRC",
    "STOx’s",
    "UBC Thunderbots",
    "Carrossel Caipira",
    "ER-Force",
    "RoboTeam Twente",
    "Cerberus",
    "Maracatronics",
    "RoboJackets",
    "Junior SuperTeam",
    "OP-AmP",
    "RobôCin",
    "UMass Minutebots",
    "Parsian",
    "Sysmic Robotics",
    "MIT Roboteam",
    "MRL",
    "Red Dragons",
    "TurtleRabbit",
    "UnBall",
    "KgpKubs",
    "Neon",
    "OrcaBOT",
    "Warthog Robotics",
    "Tritons RCSC",
    "CMμs",
    "Ri-one",
    "Ri-One",
    "A-Team",
    "RoboDragons",
    "SPbUnited",
    "TauraBOTS",
    "Unknown",
    "UTBots",
    "Roots",
    "NAELIC",
    "N.R.G",
    "TRAPS",
    "RoboFEI",
    "SeeGoals",
    "Test Team",
    "MCT Susano Logics",
    "AIS",
    "Ararabots",
    "Eagles",
    "Pequi Mecânico",
    "AMC",
    "Titans",
    "ULtron",
    "NEUIslanders",
    "RFC Cambridge",
    "The Bots",
    "URoboRus",
    "Delft Mercurians",
    "KIKS",
    "ZJUNlict",
    "nAMeC",
    "NAMeC",
    "Immortals",
    "GreenTea",
    "ibis",
    "luhbots",
    "RoboIME",
    "SSH",
    "TIGERs Mannheim"
  ],
  "autoContinue": false
}