name: STOP
description: STOP
sessions:
  - name: goalie_skill
    capacity: 1
  - name: ball_nearby_positioner_skill
    capacity: 2
  - name: sub_attacker_skill
    capacity: 1
  - name: defender
    capacity: 2
  - name: formation
    capacity: 20
