name: THEIR_INPLAY
description: THEIR_INPLAY
sessions:
  - name: goalie_skill
    capacity: 1
  - name: steal_ball
    capacity: 1
  - name: defender
    capacity: 2
  - name: marker_goal
    capacity: 20
