name: THEIR_FREE_KICK
description: THEIR_FREE_KICK
sessions:
  - name: goalie_skill
    capacity: 1
  - name: ball_nearby_positioner_skill
    capacity: 2
  - name: defender
    capacity: 2
  - name: marker
    capacity: 20
