<?xml version="1.0"?>
<package format="3">
  <name>speak_ros_aivis_plugin</name>
  <version>1.0.154</version>
  <description>Aivis Speech Engine plugin for speak_ros</description>

  <maintainer email="ibis.ssl.team@gmail.com">ibis-ssl</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>libcpprest-dev</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>speak_ros</depend>

  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <speak_ros plugin="${prefix}/plugins.xml"/>
  </export>
</package>
