events:
  - event: HALT
    session: HALT
  - event: STOP
    session: formation
  - event: THEIR_KICKOFF_PREPARATION
    session: formation
  - event: THEIR_KICKOFF_START
    session: formation
  - event: OUR_KICKOFF_PREPARATION
    session: formation
  - event: OUR_KICKOFF_START
    session: SIMPLE_ATTACK
  - event: INPLAY"
    session: defense
  - event: OUR_BALL_PLACEMENT
    session: OUR_BALL_PLACEMENT
