events:
  - event: HALT
    session: HALT
  - event: STOP
    session: STOP
  - event: THEIR_KICKOFF_PREPARATION
    session: formation
  - event: THEIR_KICKOFF_START
    session: formation
  - event: OUR_KICKOFF_PREPARATION
    session: formation
  - event: OUR_KICKOFF_START
    session: OUR_KICKOFF_START
  - event: OUR_INPLAY
    session: OUR_INPLAY
  - event: THEIR_INPLAY
    session: THEIR_INPLAY
  - event: AMBIGUOUS_INPLAY
    session: ATTACK_TEST
  - event: OUR_BALL_PLACEMENT
    session: OUR_BALL_PLACEMENT
  - event: THEIR_BALL_PLACEMENT
    session: THEIR_BALL_PLACEMENT
  - event: OUR_PENALTY_PREPARATION
    session: OUR_PENALTY_KICK
  - event: OUR_PENALTY_START
    session: OUR_PENALTY_KICK
  - event: THEIR_PENALTY_PREPARATION
    session: THEIR_PENALTY_KICK
  - event: THEIR_PENALTY_START
    session: THEIR_PENALTY_KICK
  - event: OUR_DIRECT_FREE
    session: OUR_FREE_KICK
  - event: THEIR_DIRECT_FREE
    session: THEIR_FREE_KICK
  - event: THEIR_FREE_KICK
    session: THEIR_FREE_KICK
  - event: formation
    session: formation
