events:
  - event: HALT
    session: HALT
  - event: STOP
    session: formation
  - event: THEIR_KICKOFF_PREPARATION
    session: formation
  - event: THEIR_KICKOFF_START
    session: formation
  - event: OUR_KICKOFF_PREPARATION
    session: formation
  - event: OUR_KICKOFF_START
    session: OUR_KICKOFF_START
  - event: INPLAY
    session: SIMPLE_ATTACK
  - event: OUR_BALL_PLACEMENT
    session: OUR_BALL_PLACEMENT
  - event: OUR_PENALTY_PREPARATION
    session: OUR_PENALTY_KICK
  - event: OUR_PENALTY_START
    session: OUR_PENALTY_KICK
  - event: THEIR_PENALTY_PREPARATION
    session: THEIR_PENALTY_KICK
  - event: THEIR_PENALTY_START
    session: THEIR_PENALTY_KICK
