# Movement limits for a robot

# Max absolute speed-up acceleration [m/s^2]
float32[<=1] acc_speedup_absolute_max
# Max angular speed-up acceleration [rad/s^2]
float32[<=1] acc_speedup_angular_max
# Max absolute brake acceleration [m/s^2]
float32[<=1] acc_brake_absolute_max
# Max angular brake acceleration [rad/s^2]
float32[<=1] acc_brake_angular_max
# Max absolute velocity [m/s]
float32[<=1] vel_absolute_max
# Max angular velocity [rad/s]
float32[<=1] vel_angular_max
