version: "3.1"

services:
  ssl-game-controller:
    image: "robocupssl/ssl-game-controller:3.3.1"
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:10010" # not yet overridable by autoRefs
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    volumes:
      - "./config:/config"
    network_mode: "host"
    ports:
      - "8081:8081/tcp"

  ssl-vision-client:
    image: "robocupssl/ssl-vision-client:1.6.0"
    command:
      - "-address"
      - ":8082"
      - "-visionAddress"
      - "224.5.23.2:10020"
    network_mode: "host"
    ports:
      - "8082:8082/tcp"

  ssl-status-board:
    image: "robocupssl/ssl-status-board:2.6.0"
    command:
      - "-address"
      - ":8083"
      - "-refereeAddress"
      - "224.5.23.1:11003"
    network_mode: "host"
    ports:
      - "8083:8083/tcp"

#  ssl-remote-control-yellow:
#    image: "robocupssl/ssl-remote-control:0.3.2"
#    command:
#      - "-address"
#      - ":8084"
#      - "-refereeAddress"
#      - "224.5.23.1:11003"
#      - "-team"
#      - "YELLOW"
#    network_mode: "host"
#    ports:
#      - "8084:8084/tcp"
#
#  ssl-remote-control-blue:
#    image: "robocupssl/ssl-remote-control:0.3.2"
#    command:
#      - "-address"
#      - ":8085"
#      - "-refereeAddress"
#      - "224.5.23.1:11003"
#      - "-team"
#      - "BLUE"
#    network_mode: "host"
#    ports:
#      - "8085:8085/tcp"

#  ssl-team-client-yellow:
#    image: "ssl-team-client"
#    build:
#      context: "."
#      dockerfile: cmd/ssl-team-client/Dockerfile
#    command:
#      - "-teamColor"
#      - "YELLOW"
#      - "-teamName"
#      - "Unknown"
#      - "-udpAddress"
#      - "224.5.23.1:11003"
#    network_mode: "host"

#  ssl-team-client-blue:
#    image: "ssl-team-client"
#    build:
#      context: "."
#      dockerfile: cmd/ssl-team-client/Dockerfile
#    command:
#      - "-teamColor"
#      - "BLUE"
#      - "-teamName"
#      - "Unknown"
#      - "-udpAddress"
#      - "224.5.23.1:11003"
#    network_mode: "host"
#
#  autoref-tigers:
#    image: "tigersmannheim/auto-referee:0.13.0-9-g3703023"
#    command:
#      - "-a" # active mode (connect to GC)
#      - "-hl" # headless
#      - "--visionAddress"
#      - "224.5.23.2:10020"
#      - "--refereeAddress"
#      - "224.5.23.1:11003"
#    network_mode: "host"
#
#  autoref-erforce:
#    image: "roboticserlangen/autoref:commit-5ca75e7c7883"
#    command:
#      - "--vision-port"
#      - "10020"
#      - "--gc-port"
#      - "11003"
#    network_mode: "host"

#  simulator:
#    image: "roboticserlangen/simulatorcli:commit-6a4e1c06533b"
#    environment:
#      GEOMETRY: "2020"
#      REALISM: "RC2021"
#    network_mode: "host"
#    ports:
#      - "10300/udp"
#      - "10301/udp"
#      - "10302/udp"
