version: "3.1"

services:
  ssl-game-controller:
    image: robocupssl/ssl-game-controller:3.11.2
    command:
      - -visionAddress
      - 224.5.23.2:10006
      - -trackerAddress
      - 224.5.23.2:11010 # not yet overridable by autoRefs
      - -publishAddress
      - 224.5.23.1:11111
      - -address
      - :8081
    volumes:
      - ./config:/config:rw
    network_mode: host
    ports:
      - 8081:8081/tcp

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.6.0
    command:
      - -address
      - :8082
      - -visionAddress
      - 224.5.23.2:10006
    network_mode: host
    ports:
      - 8082:8082/tcp
#
#  ssl-status-board:
#    image: robocupssl/ssl-status-board:2.6.0
#    command:
#      - -address
#      - :8083
#      - -refereeAddress
#      - 224.5.23.1:11003
#    network_mode: host
#    ports:
#      - 8083:8083/tcp
#
  ssl-remote-control-yellow:
    image: robocupssl/ssl-remote-control:0.3.2
    command:
      - -address
      - :8084
      - -refereeAddress
      - 224.5.23.1:11111
      - -team
      - YELLOW
    network_mode: host
    ports:
      - 8084:8084/tcp

#  autoref-tigers:
#    image: tigersmannheim/auto-referee:1.2.0
#    command:
#      - -a # active mode (connect to GC)
#      - -hl # headless
#      - --visionAddress
#      - 224.5.23.2:10006
#      - --refereeAddress
#      - 224.5.23.1:11003
#      - --trackerAddress
#      - 224.5.23.2:11010
#    network_mode: host

#  autoref-erforce:
#    image: roboticserlangen/autoref:commit-6f15f574ea80
#    command:
#      - --vision-port
#      - 10006
#      - --tracker-port
#      - 11010
#      - --gc-port
#      - 11003
#    network_mode: host

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
#    image: voicevox/voicevox_engine:nvidia-latest
    ports:
      - 127.0.0.1:50021:50021
