bool disable_collision_avoidance false
bool disable_goal_area_avoidance false
bool disable_placement_avoidance false
bool disable_ball_avoidance false
bool disable_field_boundary false
bool disable_crash_avoidance false

NamedFloat[] max_velocity_factors
NamedFloat final_planned_max_velocity

NamedFloat[] max_acceleration_factors
NamedFloat final_planned_max_acceleration

float32 terminal_velocity 0
uint8 priority 0

float32 theta_tolerance 0.0

bool kick_power_override false
float32 target_kick_ball_speed 0.0
float32 target_chip_distance 0.0
