[pytest]
python_files = *.py
python_functions = test_*

addopts =
    -v
    --tb=short
    --color=yes
    -p no:launch_ros
    -p no:launch_testing
    -p no:launch_pytest

testpaths = .

filterwarnings =
    ignore::DeprecationWarning
