<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>crane_debug_tools</name>
  <version>1.0.55</version>
  <description>Modern debugging tools for crane robot skills</description>
  <maintainer email="ibis.ssl.team@gmail.com">ibis ssl</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>crane_msg_wrappers</depend>
  <depend>crane_msgs</depend>
  <depend>crane_robot_skills</depend>
  <depend>crane_visualization_interfaces</depend>
  <depend>libboost-system-dev</depend>
  <depend>libgoogle-glog-dev</depend>
  <depend>libssl-dev</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rosidl_runtime_cpp</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>crane_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
