#!/usr/bin/env python3
# Copyright (c) 2026 ibis-ssl
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

"""ros2 run crane_packet_forge crane-forge ... の入口。"""

from crane_packet_forge.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
