bool disable_collision_avoidance false
bool disable_goal_area_avoidance false
bool disable_placement_avoidance false
bool disable_ball_avoidance false

float32 max_acceleration 6.0
float32 max_velocity 10.0
float32 terminal_velocity 0
uint8 priority 0

float32 theta_tolerance 0.0

float32 final_planned_max_acceleration -1.0
float32 final_planned_max_velocity -1.0

bool kick_power_override false
float target_kick_ball_speed 0.0
