name: build test

on:
  workflow_dispatch:
  pull_request:
  merge_group:

jobs:
  job:
    name: BuildAndRun
    runs-on: >-
      ${{
        (contains(github.event.pull_request.labels.*.name, 'SelfHostedRunner'))
          && fromJSON('[ "self-hosted"]')
          || fromJSON('[ "ubuntu-latest" ]')
      }}
    timeout-minutes: 30
    container: ghcr.io/ibis-ssl/crane:prebuilt
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble]
    steps:
      - name: suppress warnings
        run: |
          git config --global --add safe.directory '*'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy repository
        run: |
          mkdir -p ~/ibis_ws/src/crane
          cp -rf . ~/ibis_ws/src/crane
        shell: bash

      - name: Install dependencies
        run: |
          cd ~/ibis_ws
          vcs import src < src/crane/dependency_${{ matrix.rosdistro }}.repos

      - name: Resolve rosdep
        run: |
          cd ~/ibis_ws
          apt-get update
          rosdep update
          rosdep install -iy --from-paths src --rosdistro ${{ matrix.rosdistro }} --dependency-types=build --dependency-types=buildtool --dependency-types=test
        shell: bash

      - name: Setup Problem Matchers for GCC
        run: echo "::add-matcher::${{ github.workspace }}/.github/matchers/gcc.json"

      - name: Restore build artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            /root/ibis_ws/build
            /root/ibis_ws/install
          key: build-humble-${{ github.event.pull_request.number }}

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@v1
        with:
          base-branch: develop

      - name: Build packages
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon build --symlink-install --packages-above-and-dependencies ${{ steps.get-modified-packages.outputs.modified-packages }} --cmake-args '-DCMAKE_BUILD_TYPE=Release'
        shell: bash

      - name: Save build artifacts
        uses: actions/cache/save@v4
        with:
          path: |
            /root/ibis_ws/build
            /root/ibis_ws/install
          key: build-humble-${{ github.event.pull_request.number }}-${{ github.sha }}

      - name: Colcon test
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test
        shell: bash

      - name: Setup Problem Matchers for clang-format
        run: echo "::add-matcher::${{ github.workspace }}/.github/matchers/clang-format.json"

      - name: Show test result
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test-result --verbose
        shell: bash
