---
name: build test

on:
  workflow_dispatch:
  pull_request:

jobs:
  job:
    name: BuildAndRun
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    container: ros:${{ matrix.rosdistro }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble]
    steps:
      - name: suppress warnings
        run: |
          git config --global --add safe.directory '*'

      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo package_list=$(colcon list --names-only | sed -e ':loop; N; $!b loop; s/\n/ /g') >> $GITHUB_OUTPUT

      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"

      - name: Copy repository
        run: |
          mkdir -p ~/ibis_ws/src/crane
          cp -rf . ~/ibis_ws/src/crane
        shell: bash

      - name: Install dependencies
        run: |
          cd ~/ibis_ws
          vcs import src < src/crane/dependency.repos

      - name: Resolve rosdep
        run: |
          cd ~/ibis_ws
          apt-get update
          apt install -y python3-pip
          rosdep update --include-eol-distros
          rosdep install -iy --from-paths src --rosdistro ${{ matrix.rosdistro }}
        shell: bash

      - name: Build packages
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_CPP_MOCK_SCENARIOS=ON --packages-up-to ${{ steps.list_packages.outputs.package_list }}
        shell: bash

      - name: Colcon test
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test --packages-select ${{ steps.list_packages.outputs.package_list }}
        shell: bash

      - name: Show test result
        if: always()
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test-result --verbose
        shell: bash
