name: build test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/build_test.yaml
      - "**/**.cpp"
      - "**/**.h"
      - "**/**.hpp"
      - "**/CMakeLists.txt"
      - "**/package.xml"
      - .pre-commit-config.yaml
  merge_group:

jobs:
  job:
    name: BuildAndRun
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    container: ros:${{ matrix.rosdistro }}
    env:
      DEBIAN_FRONTEND: noninteractive
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [humble]
    steps:
      - name: suppress warnings
        run: |
          git config --global --add safe.directory '*'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy repository
        run: |
          mkdir -p ~/ibis_ws/src/crane
          cp -rf . ~/ibis_ws/src/crane
        shell: bash

      - name: Install dependencies
        run: |
          cd ~/ibis_ws
          vcs import src < src/crane/dependency.repos

      - name: Install other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl docker-compose

      - name: Download logger for scenario test
        run: |
          curl -L https://github.com/RoboCup-SSL/ssl-go-tools/releases/download/v1.5.2/ssl-log-recorder_v1.5.2_linux_amd64 -o ssl-log-recorder
          chmod +x ssl-log-recorder

      - name: docker compose pull
        run: |
          docker-compose pull -f docker/docker-compose.yaml
        shell: bash

      - name: Resolve rosdep
        run: |
          cd ~/ibis_ws
          apt-get update
          apt install -y python3-pip
          rosdep update --include-eol-distros
          rosdep install -iy --from-paths src --rosdistro ${{ matrix.rosdistro }}
        shell: bash

      - name: Setup Problem Matchers for GCC
        run: echo "::add-matcher::${{ github.workspace }}/.github/matchers/gcc.json"

      - name: Build packages
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Colcon test
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test
        shell: bash

      - name: Setup Problem Matchers for clang-format
        run: echo "::add-matcher::${{ github.workspace }}/.github/matchers/clang-format.json"

      - name: Show test result
        if: always()
        run: |
          source /opt/ros/${{ matrix.rosdistro }}/setup.bash
          cd ~/ibis_ws
          colcon test-result --verbose
        shell: bash
