name: code amount

on:
  workflow_dispatch:
  pull_request:

jobs:
  code-amount:
    runs-on: ubuntu-latest
    steps:
      - name: install cloc
        run: sudo apt-get install -y cloc

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run cloc
        run: cloc . --vcs=git
