name: docker build

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build_base:
    name: build base image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        if: steps.check_image.outputs.GITHUB_OUTPUT == ${{ steps.extract_dependencies.outputs.rosdep_checksum }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/base/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:base

  build_ccache:
    name: build ccache image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        if: steps.check_image.outputs.GITHUB_OUTPUT == ${{ steps.extract_dependencies.outputs.rosdep_checksum }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/ccache/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:ccache

  build_prebuilt:
    name: build prebuilt image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        if: steps.check_image.outputs.GITHUB_OUTPUT == ${{ steps.extract_dependencies.outputs.rosdep_checksum }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/prebuilt/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:prebuilt
